### ISSUE TITLE
functions declared during execution

### ISSUE THREAD

**Issue by missinglink** [pelias/text-analyzer#3]
I just noticed that we are declaring a bunch of functions inline during execution:

```javascript
module.exports.parse = function parse(query) {
  var getAdminPartsBySplittingOnDelim = function(queryParts) {
  ...
  var getAddressParts = function(query) {
  ...
```

It would be cleaner/more performant to declare these functions *once* outside of the `parse()` function and simply execute them from inside that scope, as it's currently written those functions are re-declared on every incoming HTTP request.

**Comment by orangejulius** [comment]
:+1: at one point it would have been hard to extract these functions because they used variables from the enclosing function, but that doesn't seem to be the case any more.
